import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/header'
import { Pacifico, Geist } from 'next/font/google'
export const metadata: Metadata = {
	title: 'Pet Bem',
	description: 'Generated by create next app'
}
const pacifico = Pacifico({
	weight: '400',
	subsets: ['latin'],
	variable: '--font-pacifico'
})
const geist = Geist({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700'],
	variable: '--font-geist'
})
export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`antialiased ${pacifico.variable} ${geist.variable}`}>
				<Header />
				{children}
			</body>
		</html>
	)
}
